---
# tasks file for kvm_firewall

- name: Stage 3 | KVM Network | Configure Firewall DNS
  iptables: action=insert chain=INPUT in_interface='{{item.name}}' destination_port=53 protocol=tcp jump=ACCEPT comment='kvm quicklab'
  with_items:
    - "{{kvm_networks}}"

- name: Stage 3 | KVM Network | Configure Firewall DNS
  iptables: action=insert chain=INPUT in_interface='{{item.name}}' destination_port=53 protocol=udp jump=ACCEPT comment='kvm quicklab'
  with_items:
    - "{{kvm_networks}}"

- name: Stage 3 | KVM Network | Configure Firewall DNS
  iptables: action=insert chain=INPUT in_interface='{{item.name}}' destination_port=67 protocol=tcp jump=ACCEPT comment='kvm quicklab'
  with_items:
    - "{{kvm_networks}}"

- name: Stage 3 | KVM Network | Configure Firewall DNS
  iptables: action=insert chain=INPUT in_interface='{{item.name}}' destination_port=67 protocol=udp jump=ACCEPT comment='kvm quicklab'
  with_items:
    - "{{kvm_networks}}"

- name: Stage 3 | KVM Network | Configure Firewall DNS
  iptables: action=insert chain=INPUT jump=ACCEPT
  with_items:
    - "{{kvm_networks}}"

- name: Stage 3 | KVM Network | Configure Firewall DNS
  iptables: action=insert chain=OUTPUT jump=ACCEPT
  with_items:
    - "{{kvm_networks}}"

- name: Stage 3 | KVM Network | Configure NAT / MASQUERADE 
  # sudo iptables -F
  # sudo iptables -t nat -F
  # # cat <<EOF
  # do_iptables_restore <<EOF
  # *nat
  # :PREROUTING ACCEPT [61:9671]
  # :POSTROUTING ACCEPT [121:7499]
  # :OUTPUT ACCEPT [132:8691]
  # -A POSTROUTING -s $NETWORK/$NETMASK -j MASQUERADE
  # COMMIT
  # # Completed on Fri Aug 24 15:20:25 2007
  # # Generated by iptables-save v1.3.6 on Fri Aug 24 15:20:25 2007
  # *filter
  # :INPUT ACCEPT [1453:976046]
  # :FORWARD ACCEPT [0:0]
  # :OUTPUT ACCEPT [1605:194911]
  # -A INPUT -i $BRIDGE -p tcp -m tcp --dport 67 -j ACCEPT
  # -A INPUT -i $BRIDGE -p udp -m udp --dport 67 -j ACCEPT
  # -A INPUT -i $BRIDGE -p tcp -m tcp --dport 53 -j ACCEPT
  # -A INPUT -i $BRIDGE -p udp -m udp --dport 53 -j ACCEPT
  # -A FORWARD -i $1 -o $1 -j ACCEPT
  # -A FORWARD -s $NETWORK/$NETMASK -i $BRIDGE -j ACCEPT
  # -A FORWARD -d $NETWORK/$NETMASK -o $BRIDGE -m state --state RELATED,ESTABLISHED -j ACCEPT
  # -A FORWARD -o $BRIDGE -j REJECT --reject-with icmp-port-unreachable
  # -A FORWARD -i $BRIDGE -j REJECT --reject-with icmp-port-unreachable
  # COMMIT
  # EOF
  #
  # iptables -t nat -A POSTROUTING -s 192.168.8.0/24 ! -d 192.168.8.0/24  -j MASQUERADE
  # note: only -o br_name not working. need -s ip/mask
  #iptables: table=nat action=append chain=POSTROUTING source={{item.ip4}} jump=MASQUERADE
  # Only the last rule get applied -> ansible problem????
  iptables: action=insert chain=FORWARD source={{item.ip4}} in_interface={{item.name}} jump=ACCEPT comment='kvm quicklab'
  iptables: action=insert chain=FORWARD destination={{item.ip4}} out_interface={{item.name}} jump=ACCEPT comment='kvm quicklab'
  iptables: 
    table: nat
    chain: POSTROUTING
    #out_interface: '{{ item.name }}'
    source: '{{ item.subnet }}'
    destination: '!{{ item.subnet }}'
    jump: MASQUERADE
    protocol: 'all'
    comment: Ansible kvm quicklab NAT Masquerade
  with_items:
    - "{{kvm_networks}}"


