# file: tasks/install_deb.yml -- install kvm packages for Debian/Ubuntu
---
#- include: 'postgresql_official_repo.yml'

- name: "Stage 1: install kvm packages for Debian"
  apt: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - bridge-utils
    - ifenslave
    - libvirt-bin
    - lldpd
    - python-libvirt
    - python-lxml
    - qemu-kvm
    - ubuntu-vm-builder
    - vlan
    - kvm-ipxe
    - libguestfs-tools 
    - guestfish
